filename <- paste0(data, "summary_children_multiple2.Rdata")
load(filename)
df_children <- df
rm(df)

# summary 
table1 <- df_children[,.(obs = .N,
                         ethnicity = mean(ethnicity) , 
                         sex = mean(sex),
                         education = mean(education),
                         age = mean(age),
                         salary = mean(salary,na.rm = TRUE),
                         firm_rank = mean(firm_rank,na.rm = TRUE),
                         con0 = mean(con_type == 0,na.rm = TRUE),
                         con1 = mean(con_type == 1,na.rm = TRUE),
                         con2 = mean(con_type == 2,na.rm = TRUE),
                         con3 = mean(con_type == 3,na.rm = TRUE),
                         con4 = mean(con_type == 4,na.rm = TRUE),
                         con5 = mean(con_type == 5,na.rm = TRUE),
                         con6 = mean(con_type == 6,na.rm = TRUE),
                         con7 = mean(con_type == 7,na.rm = TRUE),
                         con8 = mean(con_type == 8,na.rm = TRUE),
                         con123 = mean(con_type == 1|con_type == 2|con_type == 3,na.rm = TRUE),
                         con456 = mean(con_type == 4|con_type == 5|con_type == 6,na.rm = TRUE),
                         firm_rank_con1 = mean(firm_rank_con1,na.rm = TRUE),
                         firm_rank_con2 = mean(firm_rank_con2,na.rm = TRUE),
                         firm_rank_con3 = mean(firm_rank_con3,na.rm = TRUE),
                         firm_rank_con4 = mean(firm_rank_con4,na.rm = TRUE),
                         firm_rank_con5 = mean(firm_rank_con5,na.rm = TRUE),
                         firm_rank_con6 = mean(firm_rank_con6,na.rm = TRUE),
                         firm_rank_con7 = mean(firm_rank_con7,na.rm = TRUE),
                         firm_rank_con8 = mean(firm_rank_con8,na.rm = TRUE),
                         firm_rank_con123 = mean(firm_rank_con123,na.rm = TRUE),
                         firm_rank_con456 = mean(firm_rank_con456,na.rm = TRUE),
                         firms_con1 = mean(firms_con1,na.rm = TRUE),
                         firms_con2 = mean(firms_con2,na.rm = TRUE),
                         firms_con3 = mean(firms_con3,na.rm = TRUE),
                         firms_con4 = mean(firms_con4,na.rm = TRUE),
                         firms_con5 = mean(firms_con5,na.rm = TRUE),
                         firms_con6 = mean(firms_con6,na.rm = TRUE),
                         firms_con7 = mean(firms_con7,na.rm = TRUE),
                         firms_con8 = mean(firms_con8,na.rm = TRUE),
                         firms_con123 = mean(firms_con123,na.rm = TRUE),
                         firms_con456 = mean(firms_con456,na.rm = TRUE))]

table2 <- df_children[,.(obs = .N,
                         sex = mean(sex),
                         education = mean(education),
                         age = mean(age),
                         salary = mean(salary,na.rm = TRUE),
                         firm_rank = mean(firm_rank,na.rm = TRUE),
                         con0 = mean(con_type == 0,na.rm = TRUE),
                         con1 = mean(con_type == 1,na.rm = TRUE),
                         con2 = mean(con_type == 2,na.rm = TRUE),
                         con3 = mean(con_type == 3,na.rm = TRUE),
                         con4 = mean(con_type == 4,na.rm = TRUE),
                         con5 = mean(con_type == 5,na.rm = TRUE),
                         con6 = mean(con_type == 6,na.rm = TRUE),
                         con7 = mean(con_type == 7,na.rm = TRUE),
                         con8 = mean(con_type == 8,na.rm = TRUE),
                         con123 = mean(con_type == 1|con_type == 2|con_type == 3,na.rm = TRUE),
                         con456 = mean(con_type == 4|con_type == 5|con_type == 6,na.rm = TRUE),
                         firm_rank_con1 = mean(firm_rank_con1,na.rm = TRUE),
                         firm_rank_con2 = mean(firm_rank_con2,na.rm = TRUE),
                         firm_rank_con3 = mean(firm_rank_con3,na.rm = TRUE),
                         firm_rank_con4 = mean(firm_rank_con4,na.rm = TRUE),
                         firm_rank_con5 = mean(firm_rank_con5,na.rm = TRUE),
                         firm_rank_con6 = mean(firm_rank_con6,na.rm = TRUE),
                         firm_rank_con7 = mean(firm_rank_con7,na.rm = TRUE),
                         firm_rank_con8 = mean(firm_rank_con8,na.rm = TRUE),
                         firm_rank_con123 = mean(firm_rank_con123,na.rm = TRUE),
                         firm_rank_con456 = mean(firm_rank_con456,na.rm = TRUE),
                         firms_con1 = mean(firms_con1,na.rm = TRUE),
                         firms_con2 = mean(firms_con2,na.rm = TRUE),
                         firms_con3 = mean(firms_con3,na.rm = TRUE),
                         firms_con4 = mean(firms_con4,na.rm = TRUE),
                         firms_con5 = mean(firms_con5,na.rm = TRUE),
                         firms_con6 = mean(firms_con6,na.rm = TRUE),
                         firms_con7 = mean(firms_con7,na.rm = TRUE),
                         firms_con8 = mean(firms_con8,na.rm = TRUE),
                         firms_con123 = mean(firms_con123,na.rm = TRUE),
                         firms_con456 = mean(firms_con456,na.rm = TRUE)),
                      by = "ethnicity"]

table3 <- df_children[,.(obs = .N,
                          ethnicity = mean(ethnicity) , 
                          sex = mean(sex),
                          age = mean(age),
                          salary = mean(salary,na.rm = TRUE),
                          firm_rank = mean(firm_rank,na.rm = TRUE),
                          con0 = mean(con_type == 0,na.rm = TRUE),
                          con1 = mean(con_type == 1,na.rm = TRUE),
                          con2 = mean(con_type == 2,na.rm = TRUE),
                          con3 = mean(con_type == 3,na.rm = TRUE),
                          con4 = mean(con_type == 4,na.rm = TRUE),
                          con5 = mean(con_type == 5,na.rm = TRUE),
                          con6 = mean(con_type == 6,na.rm = TRUE),
                          con7 = mean(con_type == 7,na.rm = TRUE),
                          con8 = mean(con_type == 8,na.rm = TRUE),
                          con123 = mean(con_type == 1|con_type == 2|con_type == 3,na.rm = TRUE),
                          con456 = mean(con_type == 4|con_type == 5|con_type == 6,na.rm = TRUE),
                          firm_rank_con1 = mean(firm_rank_con1,na.rm = TRUE),
                          firm_rank_con2 = mean(firm_rank_con2,na.rm = TRUE),
                          firm_rank_con3 = mean(firm_rank_con3,na.rm = TRUE),
                          firm_rank_con4 = mean(firm_rank_con4,na.rm = TRUE),
                          firm_rank_con5 = mean(firm_rank_con5,na.rm = TRUE),
                          firm_rank_con6 = mean(firm_rank_con6,na.rm = TRUE),
                          firm_rank_con7 = mean(firm_rank_con7,na.rm = TRUE),
                          firm_rank_con8 = mean(firm_rank_con8,na.rm = TRUE),
                          firm_rank_con123 = mean(firm_rank_con123,na.rm = TRUE),
                          firm_rank_con456 = mean(firm_rank_con456,na.rm = TRUE),
                          firms_con1 = mean(firms_con1,na.rm = TRUE),
                          firms_con2 = mean(firms_con2,na.rm = TRUE),
                          firms_con3 = mean(firms_con3,na.rm = TRUE),
                          firms_con4 = mean(firms_con4,na.rm = TRUE),
                          firms_con5 = mean(firms_con5,na.rm = TRUE),
                          firms_con6 = mean(firms_con6,na.rm = TRUE),
                          firms_con7 = mean(firms_con7,na.rm = TRUE),
                          firms_con8 = mean(firms_con8,na.rm = TRUE),
                          firms_con123 = mean(firms_con123,na.rm = TRUE),
                          firms_con456 = mean(firms_con456,na.rm = TRUE)),
                      by = "education"]

table4 <- df_children[,.(obs = .N,
                          ethnicity = mean(ethnicity) , 
                          education = mean(education),
                          age = mean(age),
                          salary = mean(salary,na.rm = TRUE),
                          firm_rank = mean(firm_rank,na.rm = TRUE),
                          con0 = mean(con_type == 0,na.rm = TRUE),
                          con1 = mean(con_type == 1,na.rm = TRUE),
                          con2 = mean(con_type == 2,na.rm = TRUE),
                          con3 = mean(con_type == 3,na.rm = TRUE),
                          con4 = mean(con_type == 4,na.rm = TRUE),
                          con5 = mean(con_type == 5,na.rm = TRUE),
                          con6 = mean(con_type == 6,na.rm = TRUE),
                          con7 = mean(con_type == 7,na.rm = TRUE),
                          con8 = mean(con_type == 8,na.rm = TRUE),
                          con123 = mean(con_type == 1|con_type == 2|con_type == 3,na.rm = TRUE),
                          con456 = mean(con_type == 4|con_type == 5|con_type == 6,na.rm = TRUE),
                          firm_rank_con1 = mean(firm_rank_con1,na.rm = TRUE),
                          firm_rank_con2 = mean(firm_rank_con2,na.rm = TRUE),
                          firm_rank_con3 = mean(firm_rank_con3,na.rm = TRUE),
                          firm_rank_con4 = mean(firm_rank_con4,na.rm = TRUE),
                          firm_rank_con5 = mean(firm_rank_con5,na.rm = TRUE),
                          firm_rank_con6 = mean(firm_rank_con6,na.rm = TRUE),
                          firm_rank_con7 = mean(firm_rank_con7,na.rm = TRUE),
                          firm_rank_con8 = mean(firm_rank_con8,na.rm = TRUE),
                          firm_rank_con123 = mean(firm_rank_con123,na.rm = TRUE),
                          firm_rank_con456 = mean(firm_rank_con456,na.rm = TRUE),
                          firms_con1 = mean(firms_con1,na.rm = TRUE),
                          firms_con2 = mean(firms_con2,na.rm = TRUE),
                          firms_con3 = mean(firms_con3,na.rm = TRUE),
                          firms_con4 = mean(firms_con4,na.rm = TRUE),
                          firms_con5 = mean(firms_con5,na.rm = TRUE),
                          firms_con6 = mean(firms_con6,na.rm = TRUE),
                          firms_con7 = mean(firms_con7,na.rm = TRUE),
                          firms_con8 = mean(firms_con8,na.rm = TRUE),
                          firms_con123 = mean(firms_con123,na.rm = TRUE),
                          firms_con456 = mean(firms_con456,na.rm = TRUE)),
                      by = "sex"]



table <- rbind(table1,table2,table3,table4)

filename <- paste0(output, "table_summary_children_multiple2.csv")
write.csv(table,filename)

rm(table,table1,table2,table3,table4)
